# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def compute(target):
    last_two = [0, 1]
    value = 0
    while last_two[1] <= target:
        new = sum(last_two)
        last_two = [last_two[1], new]
        if new % 2 == 0:
            value += new

    return value


if __name__ == "__main__":
    print(compute(4000000))  # 4613732
